### PR TITLE
Fix: [BADA-197] Entity 자료형 수정에 따른 매개변수 수정

### LINKED ISSUE #188: [BADA-197] [BUG] 마감 기한 API 오류
### 🔖 이슈 유형 (Jira Issue Type)

Task

### 🎟️ 상위 작업 (Ticket Number)

BADA-47

### 🌳 브랜치명 (Branch)

fix/BADA-197-deadline-api-fix

### ✨ 어떤 버그인가요?

마감 기한 API 호출 시 서버 오류 발생

### 📌 어떤 상황에서 발생한 버그인가요?

서버에서 마감 기한 API 호출 시 서버 오류가 발생합니다.

### 🍀 예상 결과

정상적으로 20000 코드의 응답이 나와야 합니다.

### ✅ 체크리스트(Tasks)

- [x] 마감 기한 API 수정

### PR DESCRIPTION
**Pull request by marineAqu**
### #️⃣연관된 이슈

> close: #188
### 🚀 작업 내용

- [x] 마감 기한 API 수정

### 🔍 리뷰 요청 사항

___

### **PR Type**
bug_fix

___

### **Description**
- 마감 기한 API 자료형 오류 수정

- LocalDateTime에서 LocalDate로 변경

___

### Diagram Walkthrough

```mermaid
flowchart LR
  PostRepository -- "자료형 변경" --> PostService
```

<details> <summary><h3> File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>PostRepository.java</strong><dd><code>PostRepository에서 마감 기한 자료형 변경</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostRepository.java

<ul><li><code>findByDeadLineBefore</code> 메소드의 매개변수 자료형을 <code>LocalDateTime</code>에서 <code>LocalDate</code>로 변경</ul>

</details>

  </td>
  <td><a href="https://github.com/Ureca-Final-Project-Team2/be_badata/pull/189/files#diff-96dfa80b2598093a8977d6e90a37dce1c6504df32ff875cc039125e832b534ae">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>PostService.java</strong><dd><code>PostService에서 마감 기한 자료형 변경</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java

<ul><li><code>getPostsByDeadLine</code> 메소드에서 <code>LocalDateTime.now()</code>를 <code>LocalDate.now()</code>로 변경</ul>

</details>

  </td>
  <td><a href="https://github.com/Ureca-Final-Project-Team2/be_badata/pull/189/files#diff-9bbdab1841892045768fafd029397c8cc2310b15749b149e19fff62ca90e0655">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

</details>

___

### CODE REVIEW

File: src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostRepository.java [hunk 1]
```diff
@@ -2,12 +2,12 @@
...
 import org.springframework.data.jpa.repository.JpaRepository;
-import java.time.LocalDateTime;
+import java.time.LocalDate;
 import java.util.List;
 
 public interface PostRepository extends JpaRepository<Post, Long>, PostQueryRepository {
     List<Post> findByIsSoldOrderByCreatedAtDesc(boolean isSold);
     List<Post> findByIsSoldAndSellerIdOrderByCreatedAtDesc(boolean isSold, Long sellerId);
-    List<Post> findByDeadLineBefore(LocalDateTime time);
+    List<Post> findByDeadLineBefore(LocalDate time);
```
Comment (choyunju) [inline src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostRepository.java]: final 키워드 부탁드려요~

**Review by choyunju — APPROVED** [review]
final 만 붙여주시면 될 것같아요! 수고하셨습니다!

File: src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java [hunk 2]
```diff
@@ -88,7 +88,7 @@ public UserPostsResponse getPostsByUserId(final Long userId, final UserDetails u
 
     public PostsResponse getPostsByDeadLine(final UserDetails userdetails) {
 
-        return postsToPostResponse(postRepository.findByDeadLineBefore(LocalDateTime.now().minusDays(2)), userdetails);
+        return postsToPostResponse(postRepository.findByDeadLineBefore(LocalDate.now().minusDays(2)), userdetails);
```
[the remark this answers is not in the document]
Comment (marineAqu) [reply src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java:91]: 프론트와 임시로 2로 결정했습니다. 추후 리펙토링하겠습니다.

File: src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostRepository.java (hunk 1 above)
Comment (marineAqu) [reply src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostRepository.java]: 반영했습니다! 리뷰 감사합니다 👍
